FROM bitnami/moodle:4.5

RUN apt update && apt install -y locales locales-all
RUN apt-get -y install gcc make autoconf libc-dev pkg-config

RUN apt-get -y install php-pear
RUN pecl channel-updte pecl.php.net
RUN pecl install apcu

WORKDIR /opt/bitnami/moodle